schema_version = "1.0.0"

maintainer = "SXDIST"
type = "add-on"
id = "DZObjectBuilder"
name = "DayZ Object Builder"
tagline = "Comprehensive add-on for modding DayZ and Arma"
version = "4.2.4"
blender_version_min = "4.2.0"
website = "https://github.com/SXDIST/DayZObjectBuilder"
tags = ["Import-Export", "Game Engine", "Object"]
license = ["SPDX:GPL-3.0-or-later"]

[permissions]
files = "Import/export operations on supported file formats"
